### ISSUE TITLE
Set classes for enlarge

### ISSUE THREAD

**Issue by BLamy** [vadirn/atom-storybook#1]
Instead of setting the width statically from jquery would we be able to set a class? That way I can override it's behavior using css in my personal atom's stylesheet? 
```coffeescript
  enlarge: ->
    @isWindowResizingAllowed = false
    if @enlarged == false
      $('.atom-storybook').width($(window).width() / 2)
      @enlarged = true
    else
      $('.atom-storybook').width($(window).width() / 2.5)
      @enlarged = false
    @isWindowResizingAllowed = true
```

**Comment by vadirn** [comment]
I guess resize handle would be a better solution. I've added this feature in v1.3.0
